language: node_js
node_js:
- "14"
cache: yarn
install:
  - yarn install

jobs:
  include:
    - stage: Build and test
    # 对于master分支每个push都跑下面的俩命令
      script:
        - yarn build
        - sudo yarn test
    - stage: npm release
    # 只有tag才会被publish
      deploy:
        provider: npm
        email: '$NPM_EMAIL'
        api_key: '$NPM_TOKEN'
        skip_cleanup: true
        on:
          tags: true
branches:
  only:
    - master
    - /^v[0-9]+.*$/
notifications:
  email:
    recipients:
    - jz.livioo@gmail.com
    on_success: change
    on_failure: always