language: node_js
node_js:
- "14"
cache: yarn
install:
  - yarn install

jobs:
  include:
    - stage: Give Permission
        - sudo chmod a+rwx ./lib
    - stage: Build and test
      script:
        - yarn test
        - yarn build
    - stage: npm release
      deploy:
        provider: npm
        email: '$NPM_EMAIL'
        api_key: '$NPM_TOKEN'
        skip_cleanup: true
        on:
          tags: true
branches:
  only:
    - master
    - /^v[0-9]+.*$/
notifications:
  email:
    recipients:
    - jz.livioo@gmail.com
    on_success: change
    on_failure: always