language: node_js
node_js:
- "14"
cache: yarn
install:
  - yarn install

jobs:
  include:
    - stage: Give permissions
        # stupid travis
        # waste lot of time to give permission for test
        # this seems to be failed, even doesn't trigger travis
        # - language: bash
        #   script: 
        #     - chmod a+rwx /home/travis/build/UI-Mario/livioo-live-server/
    - stage: Build and test
    # 对于master分支每个push都跑下面的俩命令
      before_script: 
        - chmod 0555 ./node_modules/.bin/mocha
      script:
        - yarn build
        # - yarn test
    - stage: npm release
    # 只有tag才会被publish
      deploy:
        provider: npm
        email: '$NPM_EMAIL'
        api_key: '$NPM_TOKEN'
        skip_cleanup: true
        on:
          tags: true
branches:
  only:
    - master
    - /^v[0-9]+.*$/
notifications:
  email:
    recipients:
    - jz.livioo@gmail.com
    on_success: change
    on_failure: always